#Q1-1
seasons<-matrix(c("봄","여름","가을","겨울"),nrow=2)
seasons
#Q1-2
seasons<-matrix(c("봄","여름","가을","겨울"),nrow=2,byrow=T)
seasons
#Q2
seasons[,2]
#Q3
seasons_2<-rbind(seasons,c("초봄","초가을"))
seasons_2
#Q4
seasons_3<-cbind(seasons_2,c("초여름","초겨울","한겨울"))
seasons_3

#Q1

m<-matrix(c(1,5,2,6,3,7,4,8),nrow=4)
m
m[,1]
m[2,]
colnames(m)<-c('A','B')
m
mm<-cbind(m,c(9,10,11,12))
mm
n<-matrix(c(1,5,2,6,3,7,4,8),nrow=2)
n
n[1,]
n[,4]
nn<-rbind(n,c(9,10,11,12))
nn
colnames(n)<-c('A','B','C','D')
oh<-matrix(c('J','A','V','A','C','A','F','E'),nrow=2)
oh
