test_subject = ("영어", "수학", "과학", "사회")
test_subject_list = list()
test_subject_list.append(test_subject[0])
test_subject_list.append(test_subject[2])
test_subject_list.append(test_subject[3])
print(test_subject_list)
